name: Build Go Binary

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go_version: ['1.18']
        goos: ['linux', 'windows', 'darwin']
        goarch: ['amd64', 'arm64']
        exclude:
        - goos: windows
          goarch: arm64
        
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}
        
    - name: Build Go Binary
      run: |
        export GOOS=${{ matrix.goos }}
        export GOARCH=${{ matrix.goarch }}
        go env
        cd src
        go build -o WolGoWeb-${{ matrix.goos }}-${{ matrix.goarch }}-${{ matrix.go_version }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: WolGoWeb-${{ matrix.goos }}-${{ matrix.goarch }}-${{ matrix.go_version }}
        path: WolGoWeb-${{ matrix.goos }}-${{ matrix.goarch }}-${{ matrix.go_version }}
